name: Production Build and Deploy

on:
  push:
    branches: [ release ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  URL: 2nordle.com

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://${{ env.URL }}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
      
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          path: source
      
      - name: Build
        run: |
          cd source
          npm install
          npm run build
          cd ..
      
      - name: Checkout Target Repo
        uses: actions/checkout@v3
        with:
          repository: dhouty/2NORDLE-prod
          ref: gh-pages
          path: target
          token: ${{ secrets.BOT_PAT }}
      
      - name: Push Files to Target
        run: |
          cp -r source/build/* target
          cd target
          git add .
          git commit -m $GITHUB_SHA
          git push